# Jekyll 配置
title: SafeBite
description: 让每一口都安心
baseurl: "/Safe-Bite"
url: "https://0proism0.github.io"

# 构建配置
markdown: kramdown
highlighter: rouge
permalink: pretty

# 排除文件
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git
  - .gitignore
  - admin/config.yml
  - netlify.toml
